<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class Cash extends Model
{
    protected $table = 'cash';

    protected $fillable = [
        'user_id',
        'cash',
        'status_id',
    ];

    public function status()
    {
        return $this->belongsTo('App\Model\CashStatus', 'status_id');
    }

    public function user()
    {
        return $this->belongsTo('App\Model\User', 'user_id');
    }

    public static function create(array $attributes = [])
    {
        $attributes['status_id'] = 1;
        return parent::create($attributes); // TODO: Change the autogenerated stub
    }
}
